### ISSUE TITLE
Invalid character (-/45) in sequence

### ISSUE THREAD

**Issue by nekrut** [bbuchfink/diamond#25] opened 2015-12-02 14:13 UTC
This happens on a freshly downloaded nr.gz file from ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/. The formatting command was `diamond makedb --in nr.gz -d nrDec2015 --threads 8`

It is entirely possible that nr contains non-standard sequences, but the problem is that `diamond makedb`  errored out few hours after beginning the indexing and it is not clear how to "reformat" nr to get rid of this sequence. Would it be possible to:
-  have `diamond makedb` simply ignore malformed sequences instead of aborting the job
-  provide more information about the malformed sequence, so that the input can be corrected

PS. I'll try to use the `-v` option

**Comment by nekrut** [comment] 2015-12-02 16:36
Nothing in the logs when it fails: https://gist.github.com/nekrut/4582683e5105052da3dc
Produces same error on a fresh copy of nr `Error: Invalid character (-/45) in sequence`
Makes building `nr` database impossible.

**Comment by bbuchfink** [comment] 2015-12-02 18:57
Please hold on, I'll provide a fix for this.

**Comment by nekrut** [comment] 2015-12-02 20:04
Thanks!

**Comment by bbuchfink** [comment] 2015-12-03 17:13
The new version will accept - characters and turn them into X.

**Comment by gemmahoad** [comment] 2016-02-19 15:56
I have a similar issue.
```
%> ./diamond makedb --in archaea.fasta -d nr.dmnd -v
diamond v0.7.11.60
#Threads = 1
Scoring matrix = blosum62
Lambda = 0.267
K = 0.041
Gap open penalty = 11
Gap extension penalty = 1
Seg masking = 0
Database file = /home/ghoad/work/psortm/conf/analysis/sclblast/archaea/sclblast
Opening the database file... [0.0s]
Loading sequences... 4886
[0.0s]
Error: Invalid character (^/94) in sequence
```
Can you help?  archaea.fasta is a file of 9802 amino acid sequences in fasta format. The same diamond binary works ok with other fasta files I have.

Many thanks!

**Comment by AllTheOmics** [comment] 2016-04-19 19:18
I am having this same issue with the error "Invalid character (-/45) in sequence" but with the blastx command. There are some dashes in the sequences I'm running blastx on. Can I safely remove the dashes from the original sequences, or is there some way to get DIAMOND to ignore the dashes when it runs blastx?
Thanks!

**Comment by bbuchfink** [comment] 2016-04-20 07:08
You can remove the dashes. To have diamond ignore them, edit the file src/basic/value.h and change line 122 to:

const Char_representation<Nucleotide> Value_traits<Nucleotide>::from_char (Value_traits<Nucleotide>::ALPHABET_SIZE, Value_traits<Nucleotide>::ALPHABET, Value_traits<Nucleotide>::MASK_CHAR, "MRWSYKVHDBX-");

**Comment by smdabdoub** [comment] 2016-07-30 15:51
I just ran into this issue, but with the offending character missing in the output. I get the following running with blastp:

```
Opening the database...  [0.001832s]
Opening the input file...  [0.013038s]
Opening the output file...  [8.1e-05s]
Loading query sequences... 506938
 [2.62603s]
Error: Invalid character (
```

the output ends with that last line. I've run some validators on the problem file, but nothing has come up.

**Comment by bbuchfink** [comment] 2016-07-30 17:59
How big is your query file, would it be possible to send it to me?

**Comment by smdabdoub** [comment] 2016-07-30 18:22
bzipped it's ~21MB. I can upload it to google drive and email you a link to download it.

**Comment by bbuchfink** [comment] 2016-07-30 18:23
ok that would work.

**Comment by bbuchfink** [comment] 2016-07-31 12:28
The problem is in line 1013879 where there's a bunch of null characters in the file. I guess I need to fix the error message.

**Comment by smdabdoub** [comment] 2016-07-31 14:48
Ah, great, thanks. A line number in the output would definitely help as well, in addition to the character that caused the error.

**Comment by brymerr921** [comment] 2016-10-17 17:38
Hi, I downloaded protein sequences from NCBI using E-Direct and got this error:
"Error: Invalid character ( ) in sequence".  There appears to be a space between the parentheses, but I don't know how to go about finding where that would be in my very large FASTA file.

**Comment by bbuchfink** [comment] 2016-10-17 20:19
Hi,

 

you can use the latest version of diamond, it now displays the line number of the error in the file.

 

Von: brymerr921 [mailto:notifications@github.com] 
Gesendet: Montag, 17. Oktober 2016 19:39
An: bbuchfink/diamond <diamond@noreply.github.com>
Cc: bbuchfink <buchfink@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [bbuchfink/diamond] Invalid character (-/45) in sequence (#25)

 

Hi, I downloaded protein sequences from NCBI using E-Direct and got this error:
"Error: Invalid character ( ) in sequence". There appears to be a space between the parentheses, but I don't know how to go about finding where that would be in my very large FASTA file.

**Closed** 2020-08-06 22:03 UTC
