### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by andreyurch** [bbuchfink/diamond#28] opened 2015-12-19 20:34 UTC
I used diamond to align transcriptome contigs to 25 GB database of proteins. One query (with 120 000 contigs) aligned well and very fast, but next with 80 000 contigs got Segmentation fault: 11.  I concatenated first and second queries and it worked great and very fast!  
After I have downloaded set of transcriptomic contigs (30 000) and again got Segmentation fault: 11.  What is the hell?:)  I like very much this great software, help to fix it,please. 

diamond blastx -p 18 -k 1 -e 1e-20 -d uniprot_trembl.fasta -q Anadara.fa -a matches_anadara_trembl -t /home/cDNA/TEST_assembly
Segmentation fault: 11

**Comment by bbuchfink** [comment] 2015-12-19 20:36
Can you give me a download url for your input contigs and your database?

**Comment by andreyurch** [comment] 2015-12-19 20:43
Contigs are here
[mmc1.zip](https://github.com/bbuchfink/diamond/files/67602/mmc1.zip)

And here the database ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.fasta.gz

**Comment by andreyurch** [comment] 2015-12-20 09:08
And here is log of the problematic run

[diamond.log.txt](https://github.com/bbuchfink/diamond/files/67756/diamond.log.txt)

**Comment by bbuchfink** [comment] 2015-12-28 15:22
I wasn't able to reproduce the error. I ran diamond on this file using your database but it worked.

**Comment by andreyurch** [comment] 2015-12-28 15:45
Thank you for the work  with this issue. I tried to analyse this problem and now I completely don t understand what is going...   In one of the trials I also got results with this query, but after another attempt I again got segmentation fault 11 !!  So it is very unstable now.  Also I was gettting results or sometines segmentation fault with other queries. In the same time, when I used database about 300 MB size I never got these problems.  What do you think can be a problem? memmory optimization?   Do you have mac binary of dimond?

**Comment by bbuchfink** [comment] 2015-12-29 18:03
It's probably some mac-related problem. I'll try to look into it when possible, but it could take some time.

**Comment by rec3141** [comment] 2016-05-20 22:32
I'm also getting segfault 11 in MacOSX with diamond blastp even using very modest file sizes and lots of memory. The problem is worse with v0.8.1.63 than with v0.7.9.58.

I have 2 databases:
AAA.dmnd      31749788 bytes
BBB.dmnd      43210504bytes

Using v0.7.9.58:
A file with 2011426 lines and size 130509847 bytes will run against AAA but not BBB
A file with   594874 lines and size   38612827 bytes will run against AAA and BBB
A file with   594874 lines and size   38628061 bytes will run against AAA but not BBB

Using v0.8.1.63:
None of the files works against either of the databases.

This is on a MacPro with 128Gb RAM

**Comment by rec3141** [comment] 2016-05-20 22:36
cmake warnings in case they're relevant

[cmake.error.txt](https://github.com/bbuchfink/diamond/files/275537/cmake.error.txt)

**Comment by bbuchfink** [comment] 2016-05-21 09:19
I'll fix the crash problems on Mac but it's probably going to take a couple of days.

**Comment by rec3141** [comment] 2016-05-21 20:55
Thanks, I know we would appreciate it, please let me know if there is anything else I can provide.

**Comment by bbuchfink** [comment] 2016-05-23 19:52
This should be fixed in the latest version. Let me know if you still crash on Mac.

**Comment by rec3141** [comment] 2016-05-23 20:03
Alas...

./diamond blastp --db my_db -q my_query -a out -t /tmp -v

diamond v0.8.2.64 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond/releases for updates.

#CPU threads: 16
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
SEG masking = 0
SSSE3 enabled.
Reduction: [RNDQEK][C][G][H][M][F][Y][ILV][W][P][AST]
Shape configuration: 111101011101111,111011001100101111,1111001001010001001111,111100101000010010010111
#Target sequences to report alignments for: 25
Temporary directory: /tmp
Opening the database...  [2.9e-05s]
Reference = my_db.dmnd
Sequences = 40556
Letters = 15480884
Block size = 2000000000
Opening the input file...  [0.002937s]
Opening the output file...  [3.7e-05s]
Loading query sequences...  [2.61507s]
Sequences = 1005713, letters = 55602472
Building query histograms...  [0.429608s]
Allocating buffers...  [0.002347s]
Loading reference sequences...  [0.336457s]
Allocating buffers...  [0.005485s]
Initializing temporary storage...  [0.011851s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.071101s]
Building query index...  [0.194285s]
Searching alignments... Segmentation fault: 11

**Comment by bbuchfink** [comment] 2016-05-23 20:10
What Mac OS version are you using and what compiler version?

**Comment by rec3141** [comment] 2016-05-23 20:14
Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64



-- The C compiler identification is AppleClang 6.0.0.6000057
-- The CXX compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_MARCHNATIVE
-- Performing Test COMPILER_SUPPORTS_MARCHNATIVE - Success
-- Found ZLIB: /opt/local/lib/libz.dylib (found version "1.2.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /work/cryomics/apps/diamond-0.8.2/bin
cryomics:bin cryomics$ make install
Scanning dependencies of target diamond
[  3%] Building CXX object CMakeFiles/diamond.dir/src/run/main.cpp.o
[  7%] Building CXX object CMakeFiles/diamond.dir/src/basic/config.cpp.o
[ 11%] Building CXX object CMakeFiles/diamond.dir/src/util/tinythread.cpp.o
[ 14%] Building CXX object CMakeFiles/diamond.dir/src/util/compressed_stream.cpp.o
[ 18%] Building CXX object CMakeFiles/diamond.dir/src/basic/score_matrix.cpp.o
[ 22%] Building CXX object CMakeFiles/diamond.dir/src/blast/blast_filter.cpp.o
[ 25%] Building CXX object CMakeFiles/diamond.dir/src/blast/blast_seg.cpp.o
[ 29%] Building C object CMakeFiles/diamond.dir/src/blast/sm_blosum45.c.o
[ 33%] Building C object CMakeFiles/diamond.dir/src/blast/sm_blosum50.c.o
[ 37%] Building C object CMakeFiles/diamond.dir/src/blast/sm_blosum62.c.o
[ 40%] Building C object CMakeFiles/diamond.dir/src/blast/sm_blosum80.c.o
[ 44%] Building C object CMakeFiles/diamond.dir/src/blast/sm_blosum90.c.o
[ 48%] Building C object CMakeFiles/diamond.dir/src/blast/sm_pam30.c.o
[ 51%] Building C object CMakeFiles/diamond.dir/src/blast/sm_pam70.c.o
[ 55%] Building C object CMakeFiles/diamond.dir/src/blast/sm_pam250.c.o
[ 59%] Building CXX object CMakeFiles/diamond.dir/src/data/queries.cpp.o
[ 62%] Building CXX object CMakeFiles/diamond.dir/src/data/reference.cpp.o
[ 66%] Building CXX object CMakeFiles/diamond.dir/src/data/seed_histogram.cpp.o
[ 70%] Building CXX object CMakeFiles/diamond.dir/src/output/daa_record.cpp.o
[ 74%] Building CXX object CMakeFiles/diamond.dir/src/search/search.cpp.o
[ 77%] Building CXX object CMakeFiles/diamond.dir/src/util/command_line_parser.cpp.o
[ 81%] Building CXX object CMakeFiles/diamond.dir/src/util/seq_file_format.cpp.o
[ 85%] Building CXX object CMakeFiles/diamond.dir/src/util/util.cpp.o
[ 88%] Building CXX object CMakeFiles/diamond.dir/src/util/Timer.cpp.o
[ 92%] Building CXX object CMakeFiles/diamond.dir/src/basic/basic.cpp.o
[ 96%] Building CXX object CMakeFiles/diamond.dir/src/dp/floating_sw.cpp.o
[100%] Linking CXX executable diamond
[100%] Built target diamond

**Comment by bbuchfink** [comment] 2016-05-24 09:25
Could you tell me if this compiled binary works for you?
[diamond.zip](https://github.com/bbuchfink/diamond/files/279155/diamond.zip)

**Comment by rec3141** [comment] 2016-05-25 22:24
No, but I did discover that if I limit the threads it will run to completion between -p1 and -p6 but no higher.

**Comment by bbuchfink** [comment] 2016-05-26 14:49
I can't reproduce any crashes on OS X 10.11 and I don't have access to another Mac with an older version. This makes it a bit hard to track down.

**Closed** 2020-08-06 22:05 UTC
