### ISSUE TITLE
Assertion `index >= 0 && index < size()' failed.

### ISSUE THREAD

**Issue by marcelolaia** [bbuchfink/diamond#351] opened 2020-05-15 00:33 UTC
Hi,

I run diamond like this:

`diamond blastx --threads 2 --outfmt 5 --max-target-seqs 5 --evalue 1e-5 --db /home/marcelo/Diamond_DB/nr --query /home/marcelo/Google\ Drive/Mlaia/NoISeq/ExonID_GDE.fa -o /home/marcelo/Google\ Drive/Mlaia/Blastn/blastx.exons.diamond.xml`

And I got this error:
```
diamond v0.9.30.131 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 2
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /home/marcelo/Google Drive/Mlaia/Blastn
Opening the database...  [0s]
#Target sequences to report alignments for: 5
Reference = /home/marcelo/Diamond_DB/nr.dmnd
Sequences = 282858011
Letters = 101765175729
Block size = 2000000000
Opening the input file...  [0s]
Opening the output file...  [0s]
Loading query sequences...  [0.011s]
Masking queries... diamond: /build/diamond-aligner-JS1cJt/diamond-aligner-0.9.30/src/lib/Eigen/src/Core/DenseCoeffsBase.h:408: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Array<float, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = float; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Abortado
```
I did a search on Google and found nothing.

I do a test on a fasta input file whit only one seq and it worked. May be a RAM problem?
Thank you so much.

**Comment by bbuchfink** [comment] 2020-05-18 14:34
Hi, would it be possible that you made your query file available to me?

**Comment by marcelolaia** [comment] 2020-05-18 14:48
> Hi, would it be possible that you made your query file available to me?

Yes. Have you a possibility to send me a e-mail and I dropbox it to you.

**Comment by bbuchfink** [comment] 2020-05-18 15:23
Please send it to buchfink@gmail.com.

**Comment by marcelolaia** [comment] 2020-05-18 15:33
> Please send it to [buchfink@gmail.com](mailto:buchfink@gmail.com).

Done!

**Comment by bbuchfink** [comment] 2020-05-18 15:48
I tried the same with your query file and didn't get an error. Could you tell me where you downloaded Diamond from, and if you compiled from source or not? Could you also try this with the latest version?

**Comment by marcelolaia** [comment] 2020-05-18 16:04
I install it from Debian testing repositories.
```
marcelo@marcelo:~$ uname -a
Linux marcelo 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux
marcelo@marcelo:~$
```
```
marcelo@marcelo:~$ dpkg -l diamond-aligner
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Nome            Versão       Arquitectura Descrição
+++-===============-============-============-=================================>
ii  diamond-aligner 0.9.30-3     amd64        accelerated BLAST compatible loca>
marcelo@marcelo:~$ 
```

> Could you also try this with the latest version?
Yes! How is the latest version? From github?

Thank you so much!

**Comment by bbuchfink** [comment] 2020-05-18 16:10
Yes, can you try to use this one: https://github.com/bbuchfink/diamond/releases/download/v0.9.32/diamond-linux64.tar.gz

**Comment by marcelolaia** [comment] 2020-05-19 11:13
Hi @bbuchfink 
First, I upgraded diamond to diamond-aligner 0.9.32-2 in Debian Unstable. But, the issue continue:
```
marcelo@marcelo:~/Google Drive/Mlaia/Blastn$ diamond blastx --outfmt 5 --max-target-seqs 5 --evalue 1e-5 --db /media/marcelo/Seagate\ Expansion\ Drive/NCBI_DB/Diamond/nr --query /home/marcelo/Google\ Drive/Mlaia/NoISeq/ExonID_GDE.fa -o /home/marcelo/Google\ Drive/Mlaia/Blastn/blastx.exons.diamond.xml
diamond v0.9.32.133 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /home/marcelo/Google Drive/Mlaia/Blastn
Opening the database...  [0s]
#Target sequences to report alignments for: 5
Reference = /media/marcelo/Seagate Expansion Drive/NCBI_DB/Diamond/nr.dmnd
Sequences = 282858011
Letters = 101765175729
Block size = 2000000000
Opening the input file...  [0s]
Opening the output file...  [0s]
Loading query sequences...  [0.046s]
Masking queries... diamond: /build/diamond-aligner-jUHUMq/diamond-aligner-0.9.32/src/lib/Eigen/src/Core/DenseCoeffsBase.h:408: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Array<float, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = float; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
diamond: /build/diamond-aligner-jUHUMq/diamond-aligner-0.9.32/src/lib/Eigen/src/Core/DenseCoeffsBase.h:408: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Array<float, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = float; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Abortado
marcelo@marcelo:~/Google Drive/Mlaia/Blastn$
```
So, I download and execute the [https://github.com/bbuchfink/diamond/releases/download/v0.9.32/diamond-linux64.tar.gz](url)

The results are:
```
Closing the input file...  [0s]
Closing the output file...  [0.077s]
Closing the database file...  [0s]
Deallocating taxonomy...  [0s]
Total time = 6707.74s
Reported 7500 pairwise alignments, 7533 HSPs.
1610 queries aligned.
```
I will fill a Bug in the Debian Bug track system.

Thank you so much!

**Comment by ballaneypranav** [comment] 2020-05-19 15:00
Hi, @marcelolaia 
Thanks for reporting this issue. I'd like to look into this, but could you share the data you're using? If it can be shared publicly, and is not too large, please send it to us at 961013@bugs.debian.org. Otherwise, if you would prefer not to share the data publicly, could you send it to me at ballaneypranav@gmail.com? It would be easier to look into the bug with the actual data.

Regards,
Pranav

**Comment by ballaneypranav** [comment] 2020-06-03 14:03
Hi, I've been working on this and I've narrowed it down to one (or a few) sequences. Basically this error occurs whenever a query sequence is less than five nucleotides (and is independent of the length of sequences in the database file). Besides, it's not specific to the Debian package. I encountered the same error when I compiled from source downloaded from this repo, but it went away when I downloaded the compiled binary, so it's probably something to do with the way it is compiled.

When the error occurs, it is at `/src/lib/Eigen/src/Core/DenseCoeffsBase.h:408`:
`      eigen_assert(index >= 0 && index < size());`
which fails because the value of index is -1. 

I've attached the smallest dataset that can be used to reproduce the problem. Please take a look and let me know if I can help in any other way.

[diamond_dataset.zip](https://github.com/bbuchfink/diamond/files/4723827/diamond_dataset.zip)

**Comment by bbuchfink** [comment] 2020-06-11 12:20
Thanks for tracking down the error, I will provide a fix in the next release.

**Comment by bbuchfink** [comment] 2020-06-20 12:00
Should be fixed in the latest release.

**Closed by bbuchfink** 2020-06-20 12:00 UTC
