### ISSUE TITLE
diamond v0.8.14.76 - Segmentation fault: 11 

### ISSUE THREAD

**Issue by vagnerfonseca** [bbuchfink/diamond#57] opened 2016-07-15 08:29 UTC
I'm running the command
diamond blastx -d nr.dmnd -q query.fna -a matches.daa -k 1
but this showing error: Segmentation fault: 11

my dataset
[db.dmnd](http://www.ppg.uneb.br/apresentacao/db.dmnd)
[db.fasta](http://www.ppg.uneb.br/apresentacao/db.fasta)

my log
diamond v0.8.14.76 | by Benjamin Buchfink buchfink@gmail.com
Check http://github.com/bbuchfink/diamond for updates.
# CPU threads: 16

Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
# Target sequences to report alignments for: 1

Temporary directory: diamond_blast
Opening the database...  [4.1e-05s]
Opening the input file...  [0.004157s]
Opening the output file...  [4.9e-05s]
Loading query sequences...  [1.11753s]
Running complexity filter...  [1.84137s]
Building query histograms...  [0.215376s]
Allocating buffers...  [0.00045s]
Loading reference sequences...  [0.440936s]
Building reference histograms...  [0.76931s]
Allocating buffers...  [0.000469s]
Initializing temporary storage...  [0.006248s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.49554s]
Building query index...  [0.155904s]
Building seed filter...  [0.030046s]
Searching alignments... Segmentation fault: 11

**Comment by bbuchfink** [comment] 2016-07-15 08:38
I know that there's a crash bug on older Macs but I haven't been able to fix it cause I don't have access to a Mac with that OS X version. I'll try to get ahold of one but until then you probably have to find a Linux system or upgrade to the latest OS X.

**Comment by vagnerfonseca** [comment] 2016-07-15 08:41
my OS X version 10.9.5

**Comment by jjkoehorst** [comment] 2016-07-15 20:41
I have the exact same problem but under ubuntu 14.04. Blastp works fine but blastx is a no go.

/usr/local/bin/diamond blastx --no-auto-append --query tmp.fasta --db dataset_26613 --daa here

diamond v0.8.14.76 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 32
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [3.7e-05s]
Opening the input file...  [0.000118s]
Opening the output file...  [5.5e-05s]
Loading query sequences...  [0.000141s]
Running complexity filter...  [0.007897s]
Building query histograms...  [0.016469s]
Allocating buffers...  [0.003079s]
Loading reference sequences...  [0.010894s]
Building reference histograms...  [0.100561s]
Allocating buffers...  [0.002641s]
Initializing temporary storage...  [0.004512s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.099206s]
Building query index...  [0.01091s]
Building seed filter...  [0.007618s]
**Searching alignments... Segmentation fault (core dumped)**

**Comment by bbuchfink** [comment] 2016-07-15 20:53
Ok, I'll look into it.

**Comment by jjkoehorst** [comment] 2016-07-15 21:41
I am distilling the problem further and it now looks like a sequence input problem. I will need some more time to investigate this (and it is already late here). Are there limitations on headers? 

This is a sequence causing the problem...

**diamond blastx --no-auto-append -d race_a -q testheader.fasta -o test.something**

ATGTCCTCCTTAGAAAAGAAGAGCAAGAAAGACCTAAAGCTAGATGACTTATTAGAACTTAGGAGGGAGCATAAGGAACTAGAGGACCAGAGCAAGAAGTTACACGATTATCTAAATCAGAACATCTTTAGCGTATTAGACAGTACTCAGGGAAAGGAAGAAACAAAATTAGGAGAGCTCTTCAAGATTGAGGATAGTTCCTTTAACTTCTTCAAAAAACTCTCTAAGAGCGGGATCTTTGACTTCAACTTTCCTGCAATAGAGATAAATAACCTAACTAAGTACTACGGAAATAAGAATCTACCTTCTCTAGTGAATGTGTCGTTGAAGGTCCACTTTGGGGACTTCCACATAGTCATAGGTCCCAATTCTTCAGGGAAGACAACTTTATTCAACTGTATAGCTGCAAGAGAAGAATATGATGGAGAGATTCTCTTTAACTCAGTCAACTATAAAGGAGACATGCAGAAGATCTCAAAGGTCTGTGGGTTCGTCCCCTATGATCATGAATTCGACCAGTTTAGCAGCGTTGAAGATATTGTGAACACCAAGTTACAGATAATGGGCGTAGACGAGTCTTGTATCAAAAACTATCTGGATATGCAACTTAAAGCTCTATCTTTGGAAGAGACTAGAAAGACCTTGATAATTGATCTCTCCCTACTGGAGATAAGAAAGATACAACTGTTAATTGCGTTAGTCTATGACTCTCCTGTGTTGGTACTAGATCAACCTTTCTTAGGTCTTCAACATTCAGAGAAACTAGAATTGATGACTATATTAAGTAGATTTAAGGCCCAAGATAGGTCGATAGTTGTATTCACACACGAACTTTCTGATCTTCCCGCTTACTCTAATACCTGTACCTTACTATCTGAGGGAAAGGTCTACTATTCTGGATCTCTAGAAAACTTACTCCTAGAAAGCAAGAACAAATATTCGATCTCTACCTCTGATAATGATGAAGCCTTAAATATATTGGCTAAATACAGTGAGAGCTATGCAGTTAACTCTCTGAAGAATCTGATTTTCTGTACCTTTGACGGTAGACTAAACTTTTTGCTATTTCAAAGAGAGTGTGCTTCTAAAAACATAGTCTTATTAGAGATAAGAAAGATTAGTCTTGAACTTGAAGATATCTATTCCTCTATCTCTAAGGTAGGTAGTAAGACAGCAAGGATAGAGATAAATAAAAAGAAGTACTTCTCTACTAGTTAG

#CPU threads: 32
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [2.9e-05s]
Opening the input file...  [0.000129s]
Opening the output file...  [4.2e-05s]
Loading query sequences...  [0.000156s]
Running complexity filter...  [0.006129s]
Building query histograms...  [0.01557s]
Allocating buffers...  [0.003393s]
Loading reference sequences...  [0.039563s]
Building reference histograms...  [0.194967s]
Allocating buffers...  [0.00504s]
Initializing temporary storage...  [0.006584s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.175045s]
Building query index...  [0.012912s]
Building seed filter...  [0.015033s]
Searching alignments... Segmentation fault (core dumped)

**Comment by jjkoehorst** [comment] 2016-07-16 07:31
When performing a blastp on 4450 proteins (a subset of the real file) I receive the same searching alignments segmentation fault. I have the proteins zipped on a remote location for you to download. But as it is slightly sensitive data is there a way to sent you the link privately? The problem is the last sequence, if I change that to something not protein related e.g. AAZZZDBFGNH it runs flawlessly. 

Total time = 13.5049s
Reported 1586 pairwise alignments, 1650 HSSPs.
1586 queries aligned.

When running the protein alone as a single sequence it works as well

Total time = 11.8554s
Reported 1 pairwise alignments, 1 HSSPs.
1 queries aligned.

So I am not sure what is going on...

**Comment by bbuchfink** [comment] 2016-07-17 08:33
This should be fixed in the latest version.

**Comment by jjkoehorst** [comment] 2016-07-17 15:38
Indeed, compiles and runs on the mac as well on the servers here. Thanks a lot and great that you did this on a Sunday, it really helped me out finishing some nearing deadlines.

**Closed** 2020-08-14 14:51 UTC
