### ISSUE TITLE
bad_alloc even with --algo 0

### ISSUE THREAD

**Issue by cmfield** [bbuchfink/diamond#315] opened 2019-11-19 13:29 UTC
I'm running 0.9.22 (I will repeat with an update asap) as part of eggnog-mapper. I have modified the code slightly to try to improve performance by adding --block-size 20.0 -c 1. I get a crash with a bad_alloc error -6 and core dump.

`diamond blastp -d eggnog_proteins.dmnd -q ecoli_genomes.faa --more-sensitive --threads 60 --block-size 20.000000 -c 1 -e 0.001000 -o emappertmp --top 3 --query-cover 0 --subject-cover 0 --algo 0`

Any ideas?

**Comment by bbuchfink** [comment] 2019-11-19 13:32
How much memory does your system have? With these settings you will need up to 400 GB.

**Comment by cmfield** [comment] 2019-11-19 13:35
I've got 1TB to play with and I clocked it running with about 36% of that before crashing.

**Comment by bbuchfink** [comment] 2019-11-19 13:46
Can you run using `--log` and send me the whole output? Are you running on a cluster where you might be limited in allocating memory?

**Comment by cmfield** [comment] 2019-11-20 16:03
I have an interesting update. I upgraded to the latest version. I still found it crashing out with the same error so I started lowering --block-size.

With --block-size 5.0 the program has run for longer than previously, and it's using a relatively stable ~570GB RAM. My guess is that with larger block sizes it was indeed running out of memory, but with a sudden step change that I couldn't see. I suppose this could still happen, but I will log the memory usage to check for this. I can also send the log file if it still crashes.

**Comment by bbuchfink** [comment] 2019-11-21 09:17
I'd expect the memory usage to be a lot less with `-b5`. If you send me the log file I can investigate further.

**Comment by cmfield** [comment] 2019-11-27 08:42
I ran: `diamond blastp -d eggnog_proteins.dmnd -q ecoli_genomes.faa --more-sensitive --threads 60 --block-size 5.0 -c 1 -e 0.001000 -o diamondtmp --top 3 --query-cover 0 --subject-cover 0 --algo 0 --log`

The input file was 24,034,562 proteins, the longest was about ~7,000 residues. It took a few days to complete.

[diamond.log](https://github.com/bbuchfink/diamond/files/3895864/diamond.log)

[diamond_mem.zip](https://github.com/bbuchfink/diamond/files/3895865/diamond_mem.zip)

**Comment by bbuchfink** [comment] 2019-11-27 16:06
Thanks for posting the log, I will look into the memory usage issue.

**Comment by bbuchfink** [comment] 2019-12-05 13:46
I have a suspicion as to the cause of the high memory usage. Your data seems to produce a lot more hits than in the average case. I will work on handling this better but for now I recommend to just keep the block size low, as it will not make much difference in this case anyway.

One thing you could do of course is to first run Diamond in default mode (without `--more-sensitive`) and only use the unaligned queries for another round of the sensitive mode.

**Comment by bbuchfink** [comment] 2020-08-09 09:32
The issue should be fixed in versions >2.0.0, otherwise let me know.

**Closed by bbuchfink** 2020-08-09 09:32 UTC
